//
// Created by krispy1396 on 12.11.2017.
//

#ifndef ZMPO_LISTA3_NODETYPE_H
#define ZMPO_LISTA3_NODETYPE_H
enum NodeType {
    VALUE,
    VARIABLE,
    ADDITION_OPERATION,
    SUBSTRACTION_OPERATION,
    MULTIPLICATION_OPERATION,
    DIVISION_OPERATION,
    SINE_OPERATION,
    COSINE_OPERATION
};
#endif //ZMPO_LISTA3_NODETYPE_H
